[[redirects]]
from = "/baidu_verify_codeva-GMZHTetZeC.html"
to = "/baidu_verify_codeva-GMZHTetZeC.html"
status = 200
force = true

[build]
  base = "docs"
  publish = "src/.vuepress/dist"
  command = """
    node -v
    npm --version
    npm install
    npm run docs:build
    """

[build.environment]
  NODE_VERSION = "18.12.0"
  NPM_FLAGS = "--version"
