[[redirects]]
from = "/baidu_verify_codeva-GMZHTetZeC.html"
to = "/baidu_verify_codeva-GMZHTetZeC.html"
status = 200
force = true

[[redirects]]
from = "/tencent15041089569251723846.txt"
to = "/tencent15041089569251723846.txt"
status = 200
force = true

[[redirects]]
from = "/tencent15333167762936472654.txt"
to = "/tencent15333167762936472654.txt"
status = 200
force = true

[build]
  base = "docs"
  publish = "src/.vuepress/dist"
  command = """
    node -v
    npm --version
    npm install
    npm run docs:build
    """

[build.environment]
  # 升级到Node.js 20 LTS以提升性能和兼容性
  NODE_VERSION = "20.18.0"
  NPM_FLAGS = "--version"
  # 增加构建超时时间到60分钟
  BUILD_TIMEOUT = "3600"
  # 使用Jammy构建镜像（Ubuntu 22.04）以避免弃用警告
  BUILD_IMAGE = "jammy"

[functions]
  # 优化函数打包
  node_bundler = "esbuild"
